// Generated by pnpm sync:content. Do not edit manually.

export const PROFILE = {
  "summary": "Fast-learning software engineer who builds systems and automation that eliminate manual work and accelerate engineering, QA, and business teams. Excel at quickly adopting new stacks and delivering measurable results in autonomous, results-focused environments."
} as const;

export const GENERATED_WORK_EXPERIENCE = [
  {
    "id": "work-1",
    "title": "QA Automation Engineer",
    "company": "DonTouch SA",
    "location": "Chiasso",
    "start": "2026",
    "end": "present",
    "description": "- Develop and maintain integration tests (Vitest) and end-to-end tests\n  (Playwright)\n- Author YAML test specifications and leverage AI models (Claude,\n  etc.) to generate test files at scale\n- Participate in the full development lifecycle: branching, code\n  reviews, merge requests, and approvals\n- Identify, document, and track bugs and quality issues",
    "link": "#"
  },
  {
    "id": "work-2",
    "title": "Software Engineer",
    "company": "Alma Iura",
    "location": "Verona",
    "start": "2025-03",
    "end": "2026",
    "description": "Developed and maintained an internal Contract Lifecycle Management (CLM)\nplatform and digital justice integrations that automate court\ncommunications and reduce manual tasks for attorneys and legal\nsecretaries.\n- Full-stack TypeScript: Vue 3 + Express.js, separation of concerns\n  architecture.\n- Backend: Prisma ORM, PostgreSQL, REST APIs, AWS (Lambda, RDS, S3,\n  CloudFront).\n- Agile modus operandi: writing user stories, technical documentation,\n  Jira, Confluence; and providing technical support.",
    "link": "#"
  },
  {
    "id": "work-3",
    "title": "",
    "company": "",
    "location": "",
    "start": "",
    "end": "Present",
    "description": "Verona/2023-10/2025\nDesigned and implemented AI-driven tools and automation solutions to\nstreamline processes and enhance e-commerce experiences. Key projects:\n- Developed an internal AI assistant with support, creative, and\n  coding agents powered by Gemini, OpenAI, and Claude APIs.\n  > Increased team productivity by approximately 20%,\n  > reducing repetitive documentation and coding tasks for developers\n  > and support teams.\n- Built an automated QA testing tool using Gemini 2.5 Computer Use,\n  Playwright, and Python to simulate user flows and detect regressions\n  in e-commerce platforms.\n  > Reduced manual QA time by \\~40% and enabled faster\n  > test cycles, improving release confidence and frequency.\n- Created a Salesforce web app for managing SF Commerce Cloud jobs via\n  OCAPI, enabling business users to handle job operations\n  independently.\n  > Reduced IT support ticket volume by \\~60%, empowering\n  > business users to manage job operations autonomously.\n- Produced 3D garment and fabric renderings using CLO3D, Blender,\n  SketchFab, and ThreeJS for integration into the e-commerce platform.\n  > Enhanced product visualization, contributing to\n  > improved customer engagement and a more immersive shopping\n  > experience.\n- Tech stack: Python, JavaScript/TypeScript, SCSS, TailwindCSS,\n  Angular, React, Django, GCP, Jira, Confluence, Git.",
    "link": "#"
  },
  {
    "id": "work-4",
    "title": "AI Trainer",
    "company": "Scale AI",
    "location": "Remote",
    "start": "2024-09",
    "end": "2025",
    "description": "- Contributed to the training and improvement of Large Language Models\n  through high-quality data annotation and Reinforcement Learning from\n  Human Feedback (RLHF).\n- Performed detailed response evaluation and ranking to increase\n  accuracy, safety, and helpfulness of model outputs.",
    "link": "#"
  },
  {
    "id": "work-5",
    "title": "Software analyst",
    "company": "Futura Sistemi S.r.l.",
    "location": "Verona",
    "start": "2023-09",
    "end": "2023",
    "description": "- Translated customers' needs to new software features for the\n  development teams.\n- Solved various problems customers had using the company's software\n  solutions.\n- Designed and developed websites satisfying the needs of the\n  customers mainly using Figma and Wordpress.\n- Organized marketing events to show software demos to potential\n  customers.",
    "link": "#"
  },
  {
    "id": "work-6",
    "title": "",
    "company": "",
    "location": "",
    "start": "",
    "end": "Present",
    "description": "Verona/2017-06/2017\n- Developed a web platform that allows customers to configure remotely\n  parameters of Ciesse's railway energy meters EcoS.\n- Programmed in PHP, JavaScript (jQuery), AJAX, HTML, CSS, and SQL.",
    "link": "#"
  }
] as const;

export const GENERATED_EDUCATION = [
  {
    "id": "education-1",
    "school": "Coursera",
    "location": "Remote",
    "detail": "[Deep Learning"
  },
  {
    "id": "education-2",
    "school": "Academy of Applied Pharmaceutical Sciences",
    "location": "Toronto, Canada",
    "detail": "Quality Assurance and Good Manufacturing Practices"
  },
  {
    "id": "education-3",
    "school": "University of Trento",
    "location": "Italy",
    "detail": "Bachelor's Degree in Information Engineering and Business"
  },
  {
    "id": "education-4",
    "school": "San Zeno Salesian Institute",
    "location": "Verona, Italy",
    "detail": "Electrical Engineering High School Diploma-2014"
  }
] as const;

export const GENERATED_SKILLS = [
  "Languages: English (IELTS C1) and Italian (native).",
  "Tech stack: Python, JavaScript/TypeScript, SCSS, Tailwind CSS,",
  "Angular, React, Django, GCP, Jira, Confluence, Git."
] as const;

export const GENERATED_BLOG_POSTS = [
  {
    "title": "About My Work",
    "description": "",
    "link": "/blog/${post.slug}",
    "uid": "blog-${index + 1}",
    "date": "2026-05-16"
  }
] as const;
